### ISSUE TITLE
[EPIC] Have clustered advise outputs

### ISSUE THREAD

**Issue by Gkrumbach07** [thoth-station/adviser#2353]
## Problem statement

As a user of Thoth adviser, I want to be able to sort and filter through the justifications provided after an advise so that I can find display only the information that is relevant to me.

## High-level Goals

- Justifications and stack info can be grouped into smaller categories
- Justifications and stack info can have varying levels of visibility.

## Proposal description

I want to be able to filter or sort my advise output's justifications and stack info by category and priority through Thamos.

### Additional context

For example the justification bellow can have labels attached such as: `labels`: ["environment", "parameter"]
```
{
    "link": "https://thoth-station.ninja/j/env",
    "message": "No CUDA used",
    "type": "INFO"
}
```

This can be queried in an advise, so a user can get all `environment` justifications.

## Acceptance Criteria

- [ ] https://github.com/thoth-station/adviser/issues/2180
- [ ] https://github.com/thoth-station/thamos/issues/1118
- [ ] Add an additional functionality to Thamos to allow for users to hide/show filter/sort the justification and stack info output when an advise completes
