### ISSUE TITLE
Schedule solvers with priority when adviser identify unresolved packages and reschedule adviser once adviser can be re run [Tracker]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/adviser#984]
In some cases adviser can fail when it identifies unresolved Python packages. Therefore a new task is required in order to take care of the unresolved packages.

- [x] New task will send messages through Kafka (producer) containing package info for solvers.
- [x] Solver contains workflow task that will create message in solver workflow when (if) a package is synced. (https://github.com/thoth-station/solver/issues/579)
- [x] Investigator consumer will schedule an adviser run that initially failed to provide the answer to the user. (https://github.com/thoth-station/investigator/issues/63)

User-experience:
- [ ] Trigger finished webhook will provide info to user regarding the time to wait to receive an advise on that software stack.

**Comment by fridex** [comment]
I think this can can be closed, PTAL @pacospace

**Comment by pacospace** [comment]
> I think this can can be closed, PTAL @pacospace

Yes we can, we can move last task, which is only for github_app integration
